// FAVOURITE
export const ADD_TO_WATCHLIST = "ADD_TO_WATCHLIST";
export const REMOVE_FROM_WATCHLIST = "REMOVE_FROM_WATCHLIST";
export const ADD_TO_WATCHED = "ADD_TO_WATCHED";
export const REMOVE_FROM_WATCHED = "REMOVE_FROM_WATCHED";
export const MOVE_TO_WATCHED = "MOVE_TO_WATCHED";
// SEARCH
export const SET_TITLE = "SET_TITLE";
export const SET_YEAR = "SET_YEAR";
export const SET_PAGE = "SET_PAGE";
export const SET_TYPE = "SET_TYPE";
